import ProductImage from "./images/hero.jpeg";
import { v4 as uuidv4 } from "uuid";

const dummyProducts = [
  {
    title: "Sky Blue Dress",
    sku: "sky-blue-dress",
    price: "$75.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Red Dress",
    sku: "sky-blue-dress",
    price: "$115.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Black Dress",
    sku: "sky-blue-dress",
    price: "$275.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Green Hat",
    sku: "sky-blue-dress",
    price: "$15.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Scrunchie",
    sku: "sky-blue-dress",
    price: "$25.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Mask",
    sku: "sky-blue-dress",
    price: "$15.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Big Bag",
    sku: "sky-blue-dress",
    price: "$105.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Sky Blue Dress",
    sku: "sky-blue-dress",
    price: "$75.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Red Dress",
    sku: "sky-blue-dress",
    price: "$115.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Black Dress",
    sku: "sky-blue-dress",
    price: "$275.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Green Hat",
    sku: "sky-blue-dress",
    price: "$15.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Scrunchie",
    sku: "sky-blue-dress",
    price: "$25.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Mask",
    sku: "sky-blue-dress",
    price: "$15.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
  {
    title: "Big Bag",
    sku: "sky-blue-dress",
    price: "$105.00",
    imgUrl: ProductImage,
    category: "dresses",
    id: uuidv4(),
  },
];

export default dummyProducts;
